= sys3c(1)
:doctype: manpage
:manmanual: sys3c manual
:mansource: sys3c {sys3c-version}

== Name
sys3c - System 1-3 compiler

== Synopsis
[verse]
*sys3c* [_options_]
*sys3c* [_options_] --project _cfgfile_
*sys3c* [_options_] --hed _hedfile_
*sys3c* [_options_] _advfile_...
*sys3c* [_options_] --init

== Description
`sys3c` is a compiler for AliceSoft's System 1-3 game engine.

*sys3c* [_options_]::
  If none of `--project`, `--hed` nor ADV files are specified, `sys3c` reads
  configuration from `sys3c.cfg` in current directory.

*sys3c* [_options_] --project _cfgfile_::
  This form runs a compile based on the configuration file _cfgfile_.

*sys3c* [_options_] --hed _hedfile_::
  This form compiless files specified in the compile header file _hedfile_.

*sys3c* [_options_] _advfile_...::
  This form compiles the source files listed in the command line.

*sys3c* [_options_] --init::
  This form creates a new sys3c project in current directory.

== Options
*-o, --dri*=_name_::
  Write ALD output to __name__``SA.ALD``, __name__``SB.ALD``, ... (default: `out`)

*-g, --debug*::
  Generate debug information for xsystem35-sdl2.

*-E, --encoding*=_enc_::
  Specify text encoding of input files. Possible values are `sjis` and `utf8`
  (default).

*-i, --hed*=_file_::
  Read compile header file _file_.

*-h, --help*::
  Display help message about `sys3c` and exit.

*-I, --init*::
  Creates a new project in current directory. This includes a project
  configuration file, a compile header file, and a sample source file. Other
  command line options are reflected in the project settings. For example,
  *sys3c --init --sys-ver=3.8* will generate a project that targets System
  3.8.

*-p, --project*=_file_::
  Read project configuration from _file_.

*-s, --sys-ver*=_ver_::
  Sets target System version. Available values are `3.5`, `3.6`, `3.8` and `3.9`
  (default).

*-u, --unicode*::
  Generate output in UTF-8 character encoding. See xref:unicode.adoc[Unicode
  Mode document] for details.

*-V, --variables*=_file_::
  Read list of variables from _file_.

*-v, --version*::
  Display the `sys3c` version number and exit.

== Project configuration file
The project configuration file (`sys3c.cfg`) specifies a compile header file
and the other options used to compile the project. Here is an example
configuration file:

  sys_ver = 3.9
  hed = comp.hed

This instructs `sys3c` to compile for System 3.9 using the compile header
`comp.hed`.

Relative paths in configuration file are resolved based on the directory of the
configuration file.

== Compile header file
The compile header (`.hed`) file specifies a list of source files to compile.
Here is an example compile header:

  #SYSTEM35
  start.adv
  sub.adv

A compile header file starts with a `#SYSTEM35` line, followed by a list of
source files. The order in the list is important; execution starts from the
beginning of the first source file.

== See also
xref:sys3dc.adoc[*sys3dc(1)*], xref:dri.adoc[*dri(1)*]
