= sys3dc(1)
:doctype: manpage
:manmanual: sys3c manual
:mansource: sys3c {sys3c-version}

== Name
sys3dc - System 1-3 decompiler

== Synopsis
*sys3dc* [_options_] _directory_|_datfiles_...

== Description
`sys3dc` is a decompiler for AliceSoft's System 1-3 game engine. It processes
scenario files (`ADISK.DAT`, `BDISK.DAT`, etc., along with an optional
`AG00.DAT`) either from a specified directory or directly from files provided
on the command line. The decompiler generates source files that are compatible
with xref:sys3c.adoc[*sys3c(1)*], enabling reconstruction of the original game
scenarios.

== Options
*-G, --game*=_game_::
  Specify the game to decompile. Possible values are
	`system1_generic`,
	`bunkasai`,
	`crescent`,
	`rance2`,
	`rance2_hint`,
	`dps`,
	`dps_sg_fahren`,
	`dps_sg_katei`,
	`dps_sg_nobunaga`,
	`dps_sg2_antique`,
	`dps_sg2_ikenai`,
	`dps_sg2_akai`,
	`dps_sg3_rabbit`,
	`dps_sg3_shinkon`,
	`dps_sg3_sotsugyou`,
	`fukei`,
	`intruder`,
	`tengu`,
	`toushin_hint`,
	`little_vampire`,
	`little_vampire_eng`,
	`yakata`,
	`gakuen`,
	`gakuen_eng`,
	`system2_generic`,
	`ayumi_fd`,
	`ayumi_hint`,
	`ayumi_proto`,
	`dalk_hint`,
	`drstop`,
	`prog_fd`,
	`rance3`,
	`rance3_hint`,
	`sdps_maria`,
	`sdps_tono`,
	`sdps_kaizoku`,
	`yakata2`,
	`rance4_opt`,
	`system3_generic`,
	`ambivalenz_fd`,
	`ambivalenz_cd`,
	`dps_all`,
	`funnybee_cd`,
	`funnybee_fd`,
	`onlyyou`,
	`onlyyou_demo`,
	`prog_cd`,
	`prog_omake`,
	`rance41`,
	`rance41_eng`,
	`rance42`,
	`rance42_eng`,
	`ayumi_cd`,
	`ayumi_live_256`,
	`ayumi_live_full`,
	`yakata3_cd`,
	`yakata3_fd`,
	`hashirionna2`,
	`toushin2_gd`,
	`toushin2_sp`,
	`otome`,
	`ningyo`,
	`mugen`,
	`toushin2`,
	`nise_naguri`,
	`gakuen_king`.
  If this option is not specified, `sys3dc` will try to guess the game from the
  input files.

*-a, --address*::
  Prefix each line with address.

*-E, --encoding*=_enc_::
  Specify text encoding of output files. Possible values are `sjis` and `utf8`
  (default).

*-h, --help*::
  Display help message about `sys3dc` and exit.

*-o, --outdir*=_directory_::
  Generate output files under _directory_. By default, output files are
  generated in current directory.

*-u, --unicode*::
  Generate output in the Unicode mode.

*-V, --verbose*::
  Turn on verbose output.

*-v, --version*::
  Display the `sys3dc` version number and exit.

== Output
In addition to System 1-3 source files (`.adv`), `sys3dc` also generates
`sys3c.cfg` file which is a configuration file for
xref:sys3c.adoc[*sys3c(1)*]. Using this, the original scenario file can be
reconstructed by this command:

  sys3c -p sys3c.cfg

== See also
xref:sys3c.adoc[*sys3c(1)*], xref:dri.adoc[*dri(1)*]
