= sys3dc(1)
:doctype: manpage
:manmanual: sys3c manual
:mansource: sys3c

== Name
sys3dc - System 3.x decompiler

== Synopsis
*sys3dc* [_options_] _drifile_... [_system39.ain_]

== Description
`sys3dc` is a decompiler for AliceSoft's System 3.x game engine. It reads a
scenario file (usually with the suffix `SA.ALD`) and optionally a `System39.ain`
file (for System 3.9 games), and generates source files that can be compiled
with xref:sys3c.adoc[*sys3c(1)*] or the official System 3.x SDK.

== Options
*-a, --address*::
  Prefix each line with address.

*-d, --aindump*::
  Dump the contents of _system39.ain_ file to standard output, in JSON format.
  Decompilation will not be performed.

*-E, --encoding*=_enc_::
  Specify text encoding of output files. Possible values are `sjis` and `utf8`
  (default).

*-h, --help*::
  Display help message about `sys3dc` and exit.

*-o, --outdir*=_directory_::
  Generate output files under _directory_. By default, output files are
  generated in current directory.

*-s, --seq*::
  Output ADV files with sequential filenames (`0.adv`, `1.adv`, ...) instead of
  their original names.

*-V, --verbose*::
  Turn on verbose output.

*-v, --version*::
  Display the `sys3dc` version number and exit.

== Output
In addition to System 3.x source files (`{asterisk}.ADV`), `sys3dc` also generates
`sys3c.cfg` file which is a configuration file for
xref:sys3c.adoc[*sys3c(1)*]. Using this, the original scenario file can be
reconstructed by this command:

  sys3c -p sys3c.cfg

If you want to use the official System 3.x SDK, specify the generated
`sys3dc.hed` file in the `DIR.HED` file of your project directory.

== See also
xref:sys3c.adoc[*sys3c(1)*], xref:dri.adoc[*dri(1)*]
