= sys3c(1)
:doctype: manpage
:manmanual: sys3c manual
:mansource: sys3c {sys3c-version}

== Name
sys3c - System 1-3 compiler

== Synopsis
[verse]
*sys3c* [_options_]
*sys3c* [_options_] --project _cfgfile_
*sys3c* [_options_] --hed _hedfile_
*sys3c* [_options_] _advfile_...

== Description
`sys3c` is a compiler for AliceSoft's System 1-3 game engine.

*sys3c* [_options_]::
  If none of `--project`, `--hed` nor ADV files are specified, `sys3c` reads
  configuration from `sys3c.cfg` in current directory.

*sys3c* [_options_] --project _cfgfile_::
  This form runs a compile based on the configuration file _cfgfile_.

*sys3c* [_options_] --hed _hedfile_::
  This form compiless files specified in the compile header file _hedfile_.

*sys3c* [_options_] _advfile_...::
  This form compiles the source files listed in the command line.

== Options
*-o, --dri*=_name_::
  Write output to an archive named __name__. (default: `ADISK.DAT`)

*-g, --debug*::
  Generate debug information for system3-sdl2.

*-E, --encoding*=_enc_::
  Specify text encoding of input files. Possible values are `sjis` and `utf8`
  (default).

*-i, --hed*=_file_::
  Read compile header file _file_.

*-h, --help*::
  Display help message about `sys3c` and exit.

*-p, --project*=_file_::
  Read project configuration from _file_.

*-G, --game*=_game_::
  Compile for the system used in _game_. Possible values are
	`system1_generic`,
	`bunkasai`,
	`crescent`,
	`dps`,
	`dps_sg_fahren`,
	`dps_sg_katei`,
	`dps_sg_nobunaga`,
	`dps_sg2_antique`,
	`dps_sg2_ikenai`,
	`dps_sg2_akai`,
	`dps_sg3_rabbit`,
	`dps_sg3_shinkon`,
	`dps_sg3_sotsugyou`,
	`fukei`,
	`intruder`,
	`tengu`,
	`toushin_hint`,
	`little_vampire`,
	`little_vampire_eng`,
	`yakata`,
	`gakuen`,
	`gakuen_eng`,
	`system2_generic`,
	`ayumi_fd`,
	`ayumi_hint`,
	`ayumi_proto`,
	`dalk_hint`,
	`drstop`,
	`prog_fd`,
	`rance3_hint`,
	`sdps_maria`,
	`sdps_tono`,
	`sdps_kaizoku`,
	`yakata2`,
	`system3_generic`,
	`ambivalenz_fd`,
	`ambivalenz_cd`,
	`dps_all`,
	`funnybee_cd`,
	`funnybee_fd`,
	`onlyyou`,
	`onlyyou_demo`,
	`prog_cd`,
	`prog_omake`,
	`rance41`,
	`rance41_eng`,
	`rance42`,
	`rance42_eng`,
	`ayumi_cd`,
	`ayumi_live_256`,
	`ayumi_live_full`,
	`yakata3_cd`,
	`yakata3_fd`,
	`hashirionna2`,
	`toushin2_gd`,
	`toushin2_sp`,
	`otome`,
	`ningyo`,
	`mugen`.

*-u, --unicode*::
  Generate output in UTF-8 character encoding. See xref:unicode.adoc[Unicode
  Mode document] for details.

*-V, --variables*=_file_::
  Read list of variables from _file_.

*-v, --version*::
  Display the `sys3c` version number and exit.

== Project configuration file
The project configuration file (`sys3c.cfg`) specifies a compile header file
and the other options used to compile the project. Here is an example
configuration file:

  game = rance41
  hed = comp.hed

This instructs `sys3c` to compile for the game `rance41` (Rance 4.1) and to use
the compile header file `comp.hed`.

Relative paths in configuration file are resolved based on the directory of the
configuration file.

== Compile header file
The compile header (`.hed`) file specifies a list of source files to compile.
Here is an example compile header:

  start.adv
  sub.adv

The order in the list is important; execution starts from the
beginning of the first source file.

== See also
xref:sys3dc.adoc[*sys3dc(1)*], xref:dri.adoc[*dri(1)*]
