name: Windows CI
on: [push]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
        - mingw: "MINGW32"
          archive-suffix: "-32bit"
        - mingw: "MINGW64"
          archive-suffix: "-64bit"
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
    name: MSYS2 ${{ matrix.mingw }}
    steps:

    - name: Set up shell
      run: echo ::add-path::C:\msys64\usr\bin\
      shell: pwsh

    - name: Print system version
      run: |
        uname
        echo PATH: $PATH

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Create artifacts
      run: |
        mkdir artifacts
        cp */*.exe artifacts/
        cp COPYING artifacts/
        rm artifacts/*_tests.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xsys35c${{ matrix.archive-suffix }}
        path: artifacts
